version: '3'

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  postgrest:
    image: begriffs/postgrest
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
    environment:
      PGRST_DB_URI: postgres://postgres:pass@postgres:5432/authz
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
